apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: dev
spec:
  interval: 1m
  releaseName: rabbitmq
  chart:
    spec:
      chart: rabbitmq
      version: "0.1.0"
      sourceRef:
        kind: HelmRepository
        name: online-store-repo
        namespace: flux-system
  values:
    rabbitmq:
      nodeSelector:
        kubernetes.io/os: linux
      replicas: 2