apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: product
  namespace: prod
spec:
  interval: 1m
  releaseName: product
  chart:
    spec:
      chart: product
      version: "0.1.0"
      sourceRef:
        kind: HelmRepository
        name: online-store-repo
        namespace: flux-system
  values:
    productService:
      nodeSelector:
        kubernetes.io/os: linux
      ports:
      - name: http
        port: 3002
        targetPort: 3002
      replicas: 2
      productService:
        image:
          repository: acronlinestoredevuksouth001.azurecr.io/product # {"$imagepolicy": "flux-system:product-image-policy:name"}
          tag: 1.0.1 # {"$imagepolicy": "flux-system:product-image-policy:tag"}